name: Run test

on:
  push:

jobs:
  test:
    strategy:
      matrix:
        node: [10]
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: packages/uxpin-merge-cli

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}

    - name: Setting $HOME/.npmrc to install built-utils
      run: echo "${NPMRC}" > $HOME/.npmrc
      env:
        NPMRC: |
          @uxpin:registry=https://npm.pkg.github.com/
          //npm.pkg.github.com/:_authToken="${{ secrets.NPMRC_READ_TOKEN }}"

    - name: Cache merge-cli dependencies
      id: cache-merge-cli-dependencies
      uses: actions/cache@v2
      with:
        path: ./node_modules
        key: uxpin-merge-cli-dependencies-cache-${{ hashFiles('package.json') }}

    - name: Install dependencies for merge-cli
      if: steps.cache-merge-cli-dependencies.outputs.cache-hit != 'true'
      run: make dependencies

    - name: Cache test resources
      id: cache-test-resources
      uses: actions/cache@v2
      with:
        path: ./test/resources/repos
        key: uxpin-merge-cli-test-repos-${{ hashFiles('/shell_scripts/test_resources/Makefile') }}

    - name: "Allow cloning git dependencies from github"
      run: mkdir -p ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
    - name: Create test resources
      if: steps.cache-test-resources.outputs.cache-hit != 'true'
      run: make test-resources

    - name: Check
      run: make check
    - name: Build
      run: make build
    - name: Install dependencies for uxpin-merge-storybook-preset-addon
      run: cd ../uxpin-merge-storybook-preset-addon && yarn install
    - name: Test
      run: make test-ci
      timeout-minutes: 30
